echo Compiling vertex shader...
C:\VulkanSDK\1.2.154.1\Bin32\glslc.exe basic.vert -o vbasic.spv
echo Compiling fragment shader...
C:\VulkanSDK\1.2.154.1\Bin32\glslc.exe basic.frag -o fbasic.spv
echo Shader compile done.